content:
  - name: contact
    label: Contact Form Content
    type: file
    path: src/content/contact.json
    fields:
      - name: en
        label: English (en)
        type: object
        fields: &contact_fields
          - name: title
            label: Title
            type: string
          - name: intro
            label: Intro Text
            type: string
          - name: emailLabel
            label: Email Label
            type: string
          - name: phoneLabel
            label: Phone Label
            type: string
          - name: locationLabel
            label: Location Label
            type: string
          - name: location
            label: Location
            type: string
          - name: email
            label: Email Settings
            type: object
            fields:
              - name: address
                label: Email Address
                type: string
          - name: phoneNumbers
            label: Phone Numbers
            type: list
            fields:
              - name: country
                label: Country
                type: string
              - name: number
                label: Display Number
                type: string
              - name: telLink
                label: Tel Link
                type: string
              - name: flags
                label: Flag Keys
                type: list
                field:
                  type: string

      - name: es
        label: Spanish (es)
        type: object
        fields: *contact_fields


      - name: gz
        label: Galician (gz)
        type: object
        fields: *contact_fields